# Generated by Django 4.0.2 on 2022-03-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.ForeignKey(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('product', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
